import explore from '~/assets/images/blog/explore.webp';
import caption from '~/assets/images/blog/caption.webp';
import bts from '~/assets/images/blog/behind_the_scene.webp';
import stroyImage from '~/assets/images/blog/stories.webp';
import influencer from '~/assets/images/blog/influencer.webp';
import question from '~/assets/images/blog/question.webp';
import hashtag_black from '~/assets/images/blog/hashtag_black.jpg';
import authProfile from '~/assets/images/blog/blackNinjaProfile.jpg';
import choose from '~/assets/images/blog/choose.jpg';
import singing from '~/assets/images/blog/singing.jpg';
import popularHashtagImage from '~/assets/images/blog/popular_hashtags.jpg';
import { Posts } from './types';

export const blogRoutes: Posts[] = [{
  id: 1,
  title: 'Top 10 Instagram hacks',
  description: 'These nifty hacks are sure to elevate your Instagram game, whether you\'re a casual user or a social media savant. From mastering the art of Instagram stories to leveraging the power of hashtags, we\'ve got you covered. So, buckle up and get ready to embark on a journey of discovery that will transform the way you use Instagram forever.',
  path: '/blog/2023/ten-hacks',
  image: explore,
  category: 'InstaTips',
  rewards: 'recent',
  createdAt: '17 April 2023',
  type: 'Article',
  author: 'Black Ninja',
  authorImage: authProfile,
},
{
  id: 2,
  title: 'Instagram tips and tricks - 2023',
  description: 'Here are some complex and dazzling tips and tricks to create gripping and compelling content on Instagram Reels that will leave your audience in awe.',
  path: '/blog/2023/instagram-reel-tips',
  image: caption,
  category: 'InstaTips',
  rewards: 'recent',
  createdAt: '27 April 2023',
  type: 'Article',
  author: 'Black Ninja',
  authorImage: authProfile,
},
{
  id: 3,
  title: 'Instagram Story ideas',
  description: 'By using Instagram Stories creatively, you can increase engagement and reach on the platform, build stronger connections with your followers, and ultimately grow your brand.',
  path: '/blog/2023/story-ideas',
  image: stroyImage,
  category: 'InstaTips',
  rewards: 'recent',
  createdAt: '05 May 2023',
  type: 'Article',
  author: 'Black Ninja',
  authorImage: authProfile,
},
{
  id: 4,
  title: 'Approach influencer on Instagram',
  description: 'Good Influencer can help you reach a large and engaged audience, improve your brand awareness and credibility, and drive sales and conversions.',
  path: '/blog/2023/approach-influencer',
  image: influencer,
  category: 'How to',
  rewards: 'recent',
  createdAt: '15 May 2023',
  type: 'How to',
  author: 'Black Ninja',
  authorImage: authProfile,
},
{
  id: 5,
  title: 'Get more likes and followers on Instagram',
  description: 'Whether you\'re a commercial enterprise owner or a casual user, it\'s helpful to know some key notes about Instagram. This will help you get the maximum out of the platform.',
  path: '/blog/2023/get-more-views-on-instagram',
  image: question,
  category: 'How to',
  rewards: 'recent',
  createdAt: '23 May 2023',
  type: 'How to',
  author: 'Black Ninja',
  authorImage: authProfile,
},
{
  id: 6,
  title: 'About Instagram Notes',
  description: 'Instagram Notes are an clean way for users to percentage updates with their fans or a choose institution of human beings. These brief messages appear at the top of their followers, inboxes, like a thought bubble above their profile photo or icon.',
  path: '/blog/2023/about-instagram-notes',
  image: bts,
  category: 'Article',
  rewards: 'recent',
  createdAt: '30 May 2023',
  type: 'Article',
  author: 'Black Ninja',
  authorImage: authProfile,
},
{
  id: 7,
  title: 'Instagram Hashtags - FAQ"S',
  description: 'This article is about how to choose right hashtags for your post and get the answers for your hashtag related queries and make the best out of hashtags in Instagram',
  path: '/blog/2023/about-instagram-hashtags',
  image: hashtag_black,
  category: 'Article',
  rewards: 'recent',
  createdAt: '10 June 2023',
  type: 'Article',
  author: 'Black Ninja',
  authorImage: authProfile,
},
{
  id: 8,
  title: 'Effective ways to use hashtags on Instagram',
  description: 'An Article about how to choose right hashtags for Insatgram. Choosing a right hashtags for your content is important because hashtags lets you to reach wider audience',
  path: '/blog/2023/optimising-instagram-hashtags',
  image: choose,
  category: 'How to',
  rewards: 'recent',
  createdAt: '15 June 2023',
  type: 'How to',
  author: 'Black Ninja',
  authorImage: authProfile,
},
{
  id: 9,
  title: 'Add music to notes in Instagram',
  description: 'Instagram has recently announced the music feature in notes. So this article guides you to add music to your Instagram notes and make your notes better',
  path: '/blog/2023/audio-in-instagram-notes',
  image: singing,
  category: 'How to',
  rewards: 'recent',
  createdAt: '20 June 2023',
  type: 'How to',
  author: 'Black Ninja',
  authorImage: authProfile,
},
{
  id: 10,
  title: 'Popular hashtags for Instagram',
  description: 'A list of popular Instagram hashtags for your content which helps you to get more view and like. This page contains popular hashtags and its related trending hashtags',
  path: '/blog/2023/popular-hashtags',
  image: popularHashtagImage,
  category: 'Tool',
  rewards: 'recent',
  createdAt: '25 June 2023',
  type: 'Tool',
  author: 'Black Ninja',
  authorImage: authProfile,
},
{
  id: 11,
  title: 'Creative Instagram captions',
  description: 'Well-crafted captions can capture attention, evoke emotions, and encourage users to interact with your posts through likes, comments, and shares.',
  path: '/blog/2023/post-captions',
  image: popularHashtagImage,
  category: 'Tool',
  rewards: 'recent',
  createdAt: '30 June 2023',
  type: 'Tool',
  author: 'Black Ninja',
  authorImage: authProfile,
},
];
